{"name": "Create pet with wrong status", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for CreatePetShem\nstatus\n  Value error, Invalid status: wrong_status. Status must be one of [\"available\", \"pending\", \"sold\"] [type=value_error, input_value='wrong_status', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.7/v/value_error", "trace": "self = <tests.test_pet.test_create_pet.TestCreatePet object at 0x102d93110>\nget_test_name = 'tests/test_pet/test_create_pet.py::TestCreatePet::test_create_pet_with_wrong_status (setup)'\n\n    @allure.title(\"Create pet with wrong status\")\n    def test_create_pet_with_wrong_status(self, get_test_name):\n        info = next(self.pet_generator.generate_pet(status=\"wrong_status\"))\n        data = self.pet_data.prepare_pet_json(info=info)\n        print(data)\n        response = self.request.post(url=self.url.create_pet, data=data)\n    \n        self.assertions.assert_status_code(\n            response=response,\n            actual_status_code=HTTPStatus.OK,\n            test_name=get_test_name\n        )\n>       self.validator.validate_response(response=response, model=CreatePetShem.create_pet)\n\ntests/test_pet/test_create_pet.py:68: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nsrc/validator.py:17: in validate_response\n    raise e\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [200]>, model = <class 'src.shemas.pet_response_schema.CreatePetShem'>\n\n    @staticmethod\n    def validate_response(response: Response, model):\n        try:\n>           validation = model.model_validate_json(response.text)\nE           pydantic_core._pydantic_core.ValidationError: 1 validation error for CreatePetShem\nE           status\nE             Value error, Invalid status: wrong_status. Status must be one of [\"available\", \"pending\", \"sold\"] [type=value_error, input_value='wrong_status', input_type=str]\nE               For further information visit https://errors.pydantic.dev/2.7/v/value_error\n\nsrc/validator.py:12: ValidationError"}, "attachments": [{"name": "Request", "source": "7d03491d-eb04-4031-af35-c210f392ca95-attachment.json", "type": "application/json"}, {"name": "Response", "source": "b3ed9b44-ad74-4c63-af1b-51a63ef43a7c-attachment.json", "type": "application/json"}, {"name": "log", "source": "0c753aed-7534-4c57-984f-1e6f95b177a5-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4f274023-4d87-420b-8de8-1534a478714d-attachment.txt", "type": "text/plain"}], "start": 1717293320023, "stop": 1717293320540, "uuid": "55118792-1cdc-4c1f-8bdb-7cd52a394032", "historyId": "803242f90451abd777be113310e023cc", "testCaseId": "803242f90451abd777be113310e023cc", "fullName": "tests.test_pet.test_create_pet.TestCreatePet#test_create_pet_with_wrong_status", "labels": [{"name": "epic", "value": "Testing create pet"}, {"name": "parentSuite", "value": "tests.test_pet"}, {"name": "suite", "value": "test_create_pet"}, {"name": "subSuite", "value": "TestCreatePet"}, {"name": "host", "value": "Lilianas-MacBook-Air.local"}, {"name": "thread", "value": "57080-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_pet.test_create_pet"}]}